name: Lint

on:
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/python-template.yml
    with:
      python-version: "3.11"
      command: pylint --fail-under=7.0 src/main.py external/test/processor/producer.py
      use-submodules: true
